version: '3.6'
services:
  faker:
    build: .
    image: water-image
    env_file: .env
    volumes:
      - ./src:/src
    stdin_open: true
    tty: true
    ports:
      - 8000:8000

  postgres:
    image: postgres:10.1
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
